name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  Configuration: Release
  DotNetSdkVersion: 6.0.x
  PackageVersion: 1.0.0-prealpha1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DotNetSdkVersion }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration ${{ env.Configuration }} --no-restore

      - name: Run Tests
        run: dotnet test --no-restore --nologo --verbosity normal

      - name: Pack NuGet
        run: dotnet pack --configuration ${{ env.Configuration }} -p:PackageVersion=${{ env.PackageVersion }} -o ./artifacts/nupkgs
